apiVersion: v1
kind: Service
metadata:
  name: petshop-frontend
  namespace: petshop
spec:
  type: NodePort
  selector:
    app: petshop-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
