kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: petshop
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 3000
        hostPort: 3000
      - containerPort: 8080
        hostPort: 8080
      - containerPort: 5432
        hostPort: 5432
